on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish to Cloudflare Pages
        uses: ./
        with:
          # Explicit branch name needed because of: https://github.com/cloudflare/pages-action/issues/97
          branch: ${{ github.head_ref || github.ref_name }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: github-actions-example
          directory: example
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        id: publish
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"
